"""A Story's draft pull request (ADR-0021): an empty first commit and a body that claims nothing.

The body links the Story, maps every acceptance criterion as not started, names the plan and
the context pack it was built from, and discloses AI assistance. Ichnos never marks it ready.
"""

import hashlib
from typing import Any

from ichnos.github.writer import GitHubWriteError, GitHubWriter
from ichnos.honesty import claims
from ichnos.workflows.implementation import AC_RE

TRUST = {
    "human_verified": "human verified",
    "agent_verified": "agent verified",
    "generated": "generated",
    "github": "GitHub",
    "repository": "repository",
}


class ClaimError(Exception):
    """The pull request text claims finished work; nothing is proposed."""


def _section(markdown: str, heading: str) -> list[str]:
    lines, inside = [], False
    for line in markdown.splitlines():
        if line.startswith("## "):
            inside = line[3:].strip() == heading
            continue
        if inside and line.strip():
            lines.append(line)
    return lines


def _claims_in(*texts: str) -> list[str]:
    return [words for text in texts for _, words in claims(text)]


def build_draft_pr(
    *,
    story_number: int,
    story_title: str,
    story_body: str,
    plan_markdown: str,
    plan_version: int,
    plan_path: str,
    pack: dict[str, Any],
    approver: str,
    repository: str,
    base_branch: str,
    branch: str,
    model: str,
) -> tuple[dict[str, Any], str]:
    """(payload, summary) for a draft_pull_request action; raises ClaimError on any claim."""
    criteria = [(ac, " ".join(text.split())) for ac, text in AC_RE.findall(story_body)]
    rows = [f"| {ac}: {text} | Not started | None yet |" for ac, text in criteria]
    items = pack["items"]
    context = []
    for item in items:
        flags = f"; {', '.join(item['flags'])}" if item["flags"] else ""
        trust = TRUST.get(item["trust"], item["trust"])
        context.append(f"- {item['id']} {item['role']}: `{item['source']}` ({trust}{flags})")
    plan_sha = hashlib.sha256(plan_markdown.encode()).hexdigest()
    lines = [
        f"Closes #{story_number}",
        "",
        f"Draft pull request for Story #{story_number}: {story_title}. No code has changed yet: "
        "this branch starts from an empty commit, and an engineer pushes the implementation.",
        "",
        "## Acceptance criteria evidence",
        "",
        "| Criterion | Status | Evidence |",
        "| --- | --- | --- |",
        *(rows or ["| (none stated in the Story) | Not started | None yet |"]),
        "",
        "## Plan",
        "",
        " ".join(_section(plan_markdown, "Summary")) or "See the plan in Ichnos.",
        "",
        *_section(plan_markdown, "Steps"),
        "",
        f"Plan `{plan_path}`, version {plan_version}, SHA-256 `{plan_sha[:12]}`, kept in Ichnos.",
        "",
        "## Context used",
        "",
        f"Context pack `{pack['hash'][:12]}` with {len(items)} items:",
        "",
        *context,
    ]
    if pack.get("absent"):
        lines += ["", f"Not found for this Story: {', '.join(pack['absent'])}."]
    lines += [
        "",
        "## AI assistance",
        "",
        f"- Generated by Ichnos ({model}) from the context pack and the plan above.",
        f"- {approver} approved opening this draft pull request.",
        "- Ichnos does not mark pull requests ready for review and never merges them.",
    ]
    title = f"Story #{story_number}: {story_title}"
    body = "\n".join(lines) + "\n"
    message = f"Start Story #{story_number}; no code changes yet"
    found = _claims_in(title, body, message)
    if found:
        raise ClaimError("The pull request text claims finished work: " + ", ".join(found))
    payload = {
        "kind": "draft_pull_request",
        "approver": approver,
        "repository": repository,
        "base_branch": base_branch,
        "branch": branch,
        "commit_message": message,
        "title": title,
        "body": body,
        "story": story_number,
        "plan": {"path": plan_path, "version": plan_version, "sha256": plan_sha},
        "pack_hash": pack["hash"],
    }
    return payload, f"Open a draft pull request for Story #{story_number}"


def draft_stale(writer: GitHubWriter, payload: dict[str, Any], base: dict[str, Any]) -> str | None:
    if writer.branch_head(payload["branch"]) is not None:
        return f"Branch {payload['branch']} already exists."
    if writer.branch_head(payload["base_branch"]) is None:
        return f"Branch {payload['base_branch']} no longer exists."
    return None


def run_draft_pull_request(writer: GitHubWriter, payload: dict[str, Any]) -> dict[str, Any]:
    """Check the text again, start the branch from an empty commit, open the draft."""
    if _claims_in(payload["title"], payload["body"], payload["commit_message"]):
        raise GitHubWriteError("The pull request text claims finished work; nothing was written.")
    sha = writer.start_branch(
        base_branch=payload["base_branch"],
        new_branch=payload["branch"],
        message=payload["commit_message"],
    )
    pull = writer.open_pull_request(
        head=payload["branch"],
        base=payload["base_branch"],
        title=payload["title"],
        body=payload["body"],
        draft=True,
    )
    return {
        "commit_sha": sha,
        "branch": payload["branch"],
        "draft": True,
        "pull_request": {"number": pull.number, "url": pull.url},
    }
