"""link confirmations

Revision ID: 20e3ffbfa0ae
Revises: 270dfc072ade
Create Date: 2026-09-20 12:40:01.511954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e3ffbfa0ae'
down_revision: Union[str, Sequence[str], None] = '270dfc072ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_confirmations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('confirmed_by', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_link_confirmations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_confirmations')),
    sa.UniqueConstraint('workspace_id', 'link', name=op.f('uq_link_confirmations_workspace_id_link'))
    )
    with op.batch_alter_table('link_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_confirmations_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_confirmations_workspace_id'))

    op.drop_table('link_confirmations')
    # ### end Alembic commands ###
