"""check runs

Revision ID: 270dfc072ade
Revises: 44f9dea9394e
Create Date: 2026-09-20 10:44:50.013282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270dfc072ade'
down_revision: Union[str, Sequence[str], None] = '44f9dea9394e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('pull_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conclusion', sa.String(length=30), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_check_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_runs')),
    sa.UniqueConstraint('workspace_id', 'github_id', name=op.f('uq_check_runs_workspace_id_github_id'))
    )
    with op.batch_alter_table('check_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_runs_head_sha'), ['head_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_runs_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_check_runs_head_sha'))

    op.drop_table('check_runs')
    # ### end Alembic commands ###
