"""approvals as pending actions

Revision ID: 3d6604a4405c
Revises: 33a0aaf3362a
Create Date: 2026-09-19 22:27:06.614427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6604a4405c'
down_revision: Union[str, Sequence[str], None] = '33a0aaf3362a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('artifact_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('base', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('proposed_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('decision_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('result', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_approvals_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_artifact_id'))
        batch_op.drop_column('executed_at')
        batch_op.drop_column('error')
        batch_op.drop_column('result')
        batch_op.drop_column('decision_note')
        batch_op.drop_column('proposed_by')
        batch_op.drop_column('base')
        batch_op.drop_column('summary')
        batch_op.drop_column('branch')
        batch_op.drop_column('artifact_id')
        batch_op.drop_column('workspace_id')

    # ### end Alembic commands ###
