"""repository files

Revision ID: 44f9dea9394e
Revises: 3d6604a4405c
Create Date: 2026-09-20 00:41:35.826964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f9dea9394e'
down_revision: Union[str, Sequence[str], None] = '3d6604a4405c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('blob_sha', sa.String(length=40), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_repository_files_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_files')),
    sa.UniqueConstraint('workspace_id', 'path', name=op.f('uq_repository_files_workspace_id_path'))
    )
    with op.batch_alter_table('repository_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_files_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_files_workspace_id'))

    op.drop_table('repository_files')
    # ### end Alembic commands ###
