"""knowledge tables

Revision ID: 8447ca40f5f4
Revises: 7c6520e2410c
Create Date: 2026-09-19 16:58:22.234776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8447ca40f5f4'
down_revision: Union[str, Sequence[str], None] = '7c6520e2410c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('source_key', sa.String(length=500), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_chunks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunks_source', ['workspace_id', 'source_kind', 'source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('commits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('author_login', sa.String(length=100), nullable=True),
    sa.Column('authored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_commits_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commits')),
    sa.UniqueConstraint('workspace_id', 'sha', name=op.f('uq_commits_workspace_id_sha'))
    )
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commits_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('blob_sha', sa.String(length=40), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('concept_id', sa.String(length=500), nullable=True),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('trust_tier', sa.String(length=20), nullable=False),
    sa.Column('frontmatter', sa.JSON(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_documents_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('workspace_id', 'path', name=op.f('uq_documents_workspace_id_path'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('github_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('review_state', sa.String(length=30), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_github_comments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_comments')),
    sa.UniqueConstraint('workspace_id', 'kind', 'github_id', name=op.f('uq_github_comments_workspace_id_kind_github_id'))
    )
    with op.batch_alter_table('github_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_comments_item_number'), ['item_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_comments_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('github_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('state_reason', sa.String(length=30), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('milestone', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft', sa.Boolean(), nullable=True),
    sa.Column('head_ref', sa.String(length=255), nullable=True),
    sa.Column('base_ref', sa.String(length=255), nullable=True),
    sa.Column('head_sha', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_github_items_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_items')),
    sa.UniqueConstraint('workspace_id', 'number', name=op.f('uq_github_items_workspace_id_number'))
    )
    with op.batch_alter_table('github_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_items_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('source_key', sa.String(length=500), nullable=False),
    sa.Column('target_kind', sa.String(length=20), nullable=False),
    sa.Column('target_key', sa.String(length=500), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_links_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_links')),
    sa.UniqueConstraint('workspace_id', 'source_kind', 'source_key', 'target_kind', 'target_key', 'relation', 'origin', name=op.f('uq_links_workspace_id_source_kind_source_key_target_kind_target_key_relation_origin'))
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index('ix_links_target', ['workspace_id', 'target_kind', 'target_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('pull_request_commits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_pull_request_commits_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pull_request_commits')),
    sa.UniqueConstraint('workspace_id', 'pr_number', 'sha', name=op.f('uq_pull_request_commits_workspace_id_pr_number_sha'))
    )
    with op.batch_alter_table('pull_request_commits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_request_commits_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('pull_request_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('previous_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_pull_request_files_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pull_request_files')),
    sa.UniqueConstraint('workspace_id', 'pr_number', 'path', name=op.f('uq_pull_request_files_workspace_id_pr_number_path'))
    )
    with op.batch_alter_table('pull_request_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_request_files_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_request_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_request_files_workspace_id'))

    op.drop_table('pull_request_files')
    with op.batch_alter_table('pull_request_commits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_request_commits_workspace_id'))

    op.drop_table('pull_request_commits')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_workspace_id'))
        batch_op.drop_index('ix_links_target')

    op.drop_table('links')
    with op.batch_alter_table('github_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_items_workspace_id'))

    op.drop_table('github_items')
    with op.batch_alter_table('github_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_comments_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_github_comments_item_number'))

    op.drop_table('github_comments')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_workspace_id'))

    op.drop_table('documents')
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commits_workspace_id'))

    op.drop_table('commits')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_workspace_id'))
        batch_op.drop_index('ix_chunks_source')

    op.drop_table('chunks')
    # ### end Alembic commands ###
