#!/usr/bin/env python3
"""End-to-end check of the Phase 3 exit criteria against a running Ichnos.

1. A meeting note produces a BRD that passes the OKF validator (together with its index entries).
2. The BRD cites at least one source per requirement.
3. The BRD can be edited and versioned.

Runs the requirements workflow on the synced Quire meeting note through the public API, follows
it live over Server-Sent Events, writes the BRD package into a copy of the demo bundle for the
strict validator, then edits and versions the draft. With ICHNOS_LLM_PROVIDER=fake (as in CI) no
model is called. Run scripts/e2e_sync.py first so the workspace is synced. Standard library only.
"""

import argparse
import json
import shutil
import sys
import time
import urllib.error
import urllib.request
from collections.abc import Iterator
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEMO_BUNDLE = ROOT / "examples/demo-repository/docs"
DEFAULT_REPOSITORY = "MohamedAliZouariEng/quire-demo"
MEETING = "docs/meetings/2026-09-15-workspace-onboarding.md"
FINAL = {"run.completed", "run.failed", "run.interrupted"}


class Api:
    def __init__(self, base: str) -> None:
        self.base = base.rstrip("/")

    def call(self, method: str, path: str, body: Any = None) -> tuple[int, Any]:
        data = None if body is None else json.dumps(body).encode()
        request = urllib.request.Request(
            f"{self.base}{path}",
            data=data,
            method=method,
            headers={"Content-Type": "application/json"},
        )
        try:
            with urllib.request.urlopen(request, timeout=180) as response:
                return response.status, json.loads(response.read() or b"null")
        except urllib.error.HTTPError as error:
            return error.code, json.loads(error.read() or b"null")

    def events(self, path: str, timeout: float) -> Iterator[dict[str, Any]]:
        """Server-Sent Events, yielded as they arrive."""
        request = urllib.request.Request(
            f"{self.base}{path}", headers={"Accept": "text/event-stream"}
        )
        with urllib.request.urlopen(request, timeout=timeout) as response:
            for raw in response:
                line = raw.decode("utf-8").rstrip("\n")
                if line.startswith("data: "):
                    yield json.loads(line[6:])


def check(condition: bool, message: str) -> None:
    print(f"{'PASS' if condition else 'FAIL'}  {message}")
    if not condition:
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--base", default="http://127.0.0.1:8765", help="Ichnos base URL")
    parser.add_argument("--repository", default=DEFAULT_REPOSITORY, help="owner/name")
    parser.add_argument("--meeting", default=MEETING, help="synced meeting note to draft from")
    parser.add_argument("--bundle", default="/tmp/ichnos-e2e-bundle", help="output bundle")
    args = parser.parse_args()
    api = Api(args.base)

    status, config = api.call("GET", "/api/config")
    model = f"{config.get('llm_provider')} {config.get('llm_model') or ''}".strip()
    check(status == 200 and bool(config.get("llm_configured")), f"a model is configured: {model}")

    _, workspaces = api.call("GET", "/api/workspaces")
    workspace_id = next((w["id"] for w in workspaces if w["repository"] == args.repository), None)
    check(workspace_id is not None, f"a synced workspace for {args.repository} exists")

    status, source = api.call(
        "POST", f"/api/workspaces/{workspace_id}/sources/from-document", {"path": args.meeting}
    )
    check(status in (200, 201), f"the synced meeting note is a source: {source.get('title')}")

    status, run = api.call(
        "POST",
        f"/api/workspaces/{workspace_id}/runs",
        {"workflow": "requirements", "source_ids": [source["id"]]},
    )
    check(status == 202, "a requirements run started")

    kinds: list[str] = []
    started = time.monotonic()
    for event in api.events(f"/api/runs/{run['id']}/events", timeout=300):
        kinds.append(event["kind"])
        elapsed = time.monotonic() - started
        stage = event["stage"] or ""
        print(f"      {elapsed:5.1f}s  {event['kind']:16} {stage:14} {event['message'][:60]}")
        if event["kind"] in FINAL:
            break
    check(bool(kinds) and kinds[-1] == "run.completed", "live events streamed to run.completed")

    _, run = api.call("GET", f"/api/runs/{run['id']}")
    check(run["status"] == "succeeded" and bool(run["artifact_id"]), "the run succeeded")
    _, artifact = api.call("GET", f"/api/artifacts/{run['artifact_id']}")
    current = artifact["current"]
    check(
        current["origin"] == "generated" and current["findings"] == 0,
        f"draft v1 generated by {current['actor']}, with no OKF findings",
    )

    content: str = current["content"]
    sections = content.split("\n## R-")[1:]
    uncited = [s.split("\n", 1)[0] for s in sections if "[^" not in s.split("\n# ", 1)[0]]
    check(bool(sections) and not uncited, f"EXIT 2: all {len(sections)} requirements cite a source")

    bundle = Path(args.bundle)
    shutil.rmtree(bundle, ignore_errors=True)
    shutil.copytree(DEMO_BUNDLE, bundle)
    result = run["outputs"]["result"]
    target = bundle / result["path"].removeprefix("docs/")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    for entry in result.get("index_entries", []):
        index = bundle / entry["index"].removeprefix("docs/")
        existing = (
            index.read_text(encoding="utf-8").rstrip("\n")
            if index.exists()
            else f"# {entry['heading']}\n"
        )
        index.write_text(existing + "\n" + entry["entry"] + "\n", encoding="utf-8")
    check(target.exists(), f"EXIT 1 (pending the validator): BRD package written to {bundle}")

    edited = content.replace("# Summary\n\n", "# Summary\n\nReviewed by the end-to-end check.\n\n", 1)
    status, saved = api.call(
        "POST",
        f"/api/artifacts/{artifact['id']}/versions",
        {"content": edited, "base_version": 1, "note": "End-to-end edit"},
    )
    ok = status == 201 and saved["current"]["number"] == 2 and saved["current"]["origin"] == "edited"
    check(ok, "the edit was saved as v2 (edited)")
    _, first = api.call("GET", f"/api/artifacts/{artifact['id']}/versions/1")
    check(first["content"] == content, "v1 is unchanged")
    status, _ = api.call(
        "POST",
        f"/api/artifacts/{artifact['id']}/versions",
        {"content": content + "\nStale.\n", "base_version": 1},
    )
    check(status == 409, "EXIT 3: the BRD is edited and versioned; a stale save is refused")

    print(f"\nNow validate the package: validate_okf.py {bundle} --strict (exit criterion 1).")


if __name__ == "__main__":
    main()
