#!/usr/bin/env bash
# Create or update the Ichnos label set on a GitHub repository.
# Usage: scripts/sync_labels.sh [owner/repo]   (defaults to the current repo)
set -euo pipefail
REPO="${1:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"
echo "Syncing Ichnos labels to $REPO"

while IFS='|' read -r name color description; do
  [[ -z "$name" || "$name" == \#* ]] && continue
  gh label create "$name" --repo "$REPO" --color "$color" \
    --description "$description" --force
done <<'LABELS'
# name|color|description
type:initiative|5319e7|High-level product outcome or investment area
type:epic|8250df|Coherent deliverable connected to an Initiative
type:story|0969da|Implementable unit of work with acceptance criteria
type:bug|d73a4a|Defect in existing behaviour
status:draft|ededed|Not yet reviewed
status:needs-review|fbca04|Waiting for human review
status:approved|0e8a16|Approved by a human
status:ready-for-implementation|1d76db|Approved and ready to be picked up
status:in-progress|c5def5|Work has started
status:blocked|b60205|Blocked by a dependency or open question
status:done|6e7781|Completed
agent:generated|bfd4f2|Content generated by the Ichnos agent workflow
priority:p0|b60205|Critical: do now
priority:p1|d93f0b|High
priority:p2|fbca04|Medium
priority:p3|c2e0c6|Low
LABELS
